# -*- coding: utf-8 -*-
"""BeautifulSoup

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zI3zr0Es0t1RrIScbciZzXd-pQDz5ijL
"""

# Para obtener info por año
year = '2019'
url_link = 'https://www.basketball-reference.com/leagues/NBA_{}_per_game.html'

# URL + año
url = url_link.format(year)
url

years = [2015,2016,2017,2018,2019]
url_link = 'https://www.basketball-reference.com/leagues/NBA_{}_per_game.html'

for year in years:
  url = url_link.format(year)
  print(url)

#Jugadores
url = 'https://www.basketball-reference.com/leagues/NBA_2019_per_game.html'

import pandas as pd

df = pd.read_html(url, header = 0)
df

len(df)

df[0]

df2019 = df[0]

df2019[df2019.Age == 'Age']

len(df2019[df2019.Age == 'Age'])

df = df2019.drop(df2019[df2019.Age == 'Age'].index)

df.shape

"""Análisis (a parte)"""

import seaborn as sns

sns.distplot(df.PTS, 
             kde=False)

sns.distplot(df.PTS, 
             kde=False,
             hist_kws=dict(edgecolor="black", linewidth=2))

sns.distplot(df.PTS,
             kde=False,
             hist_kws=dict(edgecolor="black", linewidth=2),
             color='#00BFC4')

